name: CrafterTextEnv-v1
action_space_type: harder
env_reward: True
seed: 1
dying: True
length: 400
similarity_threshold: 0.99
check_ac_success: False
novelty_bias: False
goal_generator: ConstantGoalGenerator #Options: "LLMGoalGenerator", "ConstantGoalGenerator", "ConstantSamplerGoalGenerator"
language_model: None  #Options: "mistral7binstruct", "testllm"
frame_stack: 4